<?php

namespace AppBundle\Repository;

/**
 * GraphSchemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraphSchemaRepository extends \Doctrine\ORM\EntityRepository
{
}
