<?php

namespace AppBundle\Repository\Anytest;

/**
 * SometestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SometestRepository extends \Doctrine\ORM\EntityRepository
{
}
